### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by zeroszzk** [luigifreda/slamplay#2]
I followed the steps in quick start to compile, and the first two steps were completed, but I encountered the following problems when compiling. I tried to find information to solve them, but I was ultimately unsuccessful.

My system is Ubuntu20.04.6 LTS. Using the method provided in step two, I encountered the following problems when installing OpenCV4.x (1, 2, 3). When installing 3.x, I encountered an incompatibility problem.
1，
slamplay-master/frontend/features/test_opencv_features_extract_match_homography.cpp:261:24: error: ‘cv::SIFT’ has not been declared
  261 |         detector = cv::SIFT::create(nfeatures, nlevels);

2，
slamplay-master/frontend/motion_estimation_2D_2D/test_pose_estimation_2d2d.cpp:162:64: error: ‘USAC_MAGSAC’ is not a member of ‘cv’
  162 |   essential_matrix = findEssentialMat(points1, points2, K, cv::USAC_MAGSAC);

3，
/usr/local/include/DBoW3/Vocabulary.h:303:43: error: ISO C++17 does not allow dynamic exception specifications
  303 |   void fromStream(  std::istream &str )   throw(std::exception);

**Comment by luigifreda** [comment]
Hi,
Thanks for the feedback. 
Could you please try the following steps?
1. remove any opencv folder from the thirdparty folder 
2. launch install_local_opencv.sh as is on the repository (without any changes)

If you get any error, please, copy here the script/build output.

**Comment by zeroszzk** [comment]
> Hi, Thanks for the feedback. Could you please try the following steps?
> 
>     1. remove any opencv folder from the thirdparty folder
> 
>     2. launch install_local_opencv.sh as is on the repository (without any changes)
> 
> 
> If you get any error, please, copy here the script/build output.

Thank you for your reply. I followed your advice and recompiled OpenCV, and installed OpenCV contrib module at the same time. After rebuilding, the compilation was successful.
